name: vision_rop
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  csv: ^5.1.1
  image_picker: ^0.8.4+4
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.8
  url_launcher: ^6.0.12
  flutter_carousel_widget: ^2.0.0
  image: ^4.3.0
  platform: ^3.0.0
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/crop_manure_data.csv
    - assets/images/
    - assets/model/plant_disease_model.tflite
    - assets/model/labels.txt
    - assets/translations/
    - assets/logo.jpg
